name: Terraform Scanning
on:
  pull_request:
  push:
    paths:
      - "terraform/*"
      - ".github/workflows/*"
    branches:
      - "main"

jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    name: AWS Terraform Security Scan
    steps:
      - uses: actions/checkout@v3

      - name: Security scan Terraform code 
        uses: mondoohq/actions/terraform@main
        with:
          service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
          path: ./terraform